INSERT INTO _dict_description_items(Name, InsertTime) VALUES (N'Beau Jeu Top Glider Adidas to replika oficjalnej piłki meczowej Adidas Beau Jeu zaprojektowanej na Mistrzostwa Europy Francja 2016. Wykonana z wytrzymałego materiału syntetycznego, precyzyjnie szyta doskonale sprawdza się w grze rekreacyjnej i treningowej na boiskach trawiastych.', GETDATE());

INSERT INTO _dict_description_items(Name, InsertTime) VALUES (N'Narty, z którymi jesteś zawsze przygotowana na każde warunki. MYA 3 to łatwe i wszechstronne narty na relaksacyjne zjazdy i niedzielne szusy. Dzięki konstrukcji Power Carbon Jacket oraz technologii ERA 3.0 i przezroczystemu ślizgowi UHM C jazda na nich zawsze będzie dla Ciebie lekka, przyjemna i komfortowa. W sprzedaży z najwyższej jakości lekkimi i uniwersalnymi wiązaniami Head MYA 9 LRX stworzonymi specjalnie dla kobiet.', GETDATE());

INSERT INTO _dict_description_items(Name, InsertTime) VALUES (N'Rower M9223 posiada pokrętło do ręcznej zmiany obciążenia. Wygodne umiejscowienie pokrętła na kolumnie kierownicy sprawia, że regulowanie siły hamowania nie zaburza rytmu jazdy. Intensywność treningu pozostaje pod pełną kontrolą osoby ćwiczącej, wartość pulsu rejestrowana jest przez dotykowe czujniki umieszczone na kierownicy. Sensory pozwalają również dokonywać pomiaru tkanki tłuszczowej.', GETDATE());

INSERT INTO _dict_description_items(Name, InsertTime) VALUES (N'Zaawansowany męski sportowy t-shirt Under Armour. Rozciągliwy, przylegający i opięty (tzw. „druga skóra”), w którym poprawisz wyniki swoich treningów. Krój Compression sprawia, że w czasie wysiłku wykorzystujesz większy potencjał swojej siły i wytrzymałości. Optymalizuje pracę mięśni, które stają się maksymalnie wydajne. Dzianina jest lekka, miękka i wyjątkowo elastyczna. Dzięki zastosowaniu HeatGear® transmituje wilgoć na zewnątrz materiału, skąd błyskawicznie wysycha. Panele boczne z przewiewnego meshu poprawiają wentylację, a płaskie szwy zapobiegają uwieraniu.', GETDATE());

INSERT INTO _dict_description_items(Name, InsertTime) VALUES (N'Siódma odsłona popularnych butów do biegania Asics Patriot. Polecane dla początkujących biegaczy ze stopą neutralną i lekko supinującą. Buty pozwalają wyczuć podłoże i pomagają optymalnie przetaczać stopę w trakcie treningu. Piankowa podeszwa dobrze amortyzuje, a lekka konstrukcja zapewnia idealne dopasowanie i stabilizację.', GETDATE());

INSERT INTO _dict_description_items(Name, InsertTime) VALUES (N'Bądź jeszcze szybszy i uprzedź przeciwnika w ulepszonej, odświeżonej wersji korków Nike Mercurial Vortex. Uwolnij eksplozję prędkości, by osiągnąć piekielne przyspieszenie i zostawić za sobą rywali. Korki Mercurial Vortex II to doskoanła stabilność oraz czucie i kontrola dzięki lekkiej i cienkiej cholewce. Wzmocniona pięta z modelowanym kołnierzem zapewnia wsparcie, a miękka wkładka prawidłowe ułożenie stopy, by każdy ruch przynosił maksimum korzyści.', GETDATE());

INSERT INTO _dict_description_items(Name, InsertTime) VALUES (N'Wiesz dlaczego stacjonarny rowerek treningowy jest tak popularny? Dlaczego jest najchętniej wybieranym narzędziem m.in. do pozbycia się nadmiaru kilogramów, wysmuklenia sylwetki i poprawy kondycji? Przede wszystkim jest wygodną i skuteczną formą treningu, który odbywasz we własnym domu - nie przejmujesz się chociażby złą pogodą - wyszczuplasz swoje ciało i spalasz kalorie nawet oglądając ulubiony program telewizyjny.', GETDATE());

INSERT INTO _dict_description_items(Name, InsertTime) VALUES (N'Podstawowy model rowerka o ergonomicznej konstrukcji z wygodnym siodełkiem przeznaczony do domowego treningu. Rower Rio HS-010H posiada mechaniczny system oporu, poziom trudności ustawiasz korzystając z pokrętła do płynnej regulacji, umieszczonego na kolumnie kierownicy. Pedały z paskami stabilizują stopy podczas jazdy. Rowerek HS-010H Rio wyposażony jest w komputer wyświetlający najważniejsze informacje o prowadzonym treningu.', GETDATE());

INSERT INTO _dict_description_items(Name, InsertTime) VALUES (N'Komplet oficjalnych piłek tenisowych ATP World Tour. Odbijają się jak nowe o wiele dłużej niż inne. 
Head ATP to ikona, która spełnia najostrzejsze standardy międzynarodowych federacji tenisowych ATP i ITF. Piłki produkowane są w nowej technologii Encore™ i SmartOptik™. 
Sukces rozgrywek na korcie zależny jest od zgrania i współdziałania trzech elementów: zawodnika, rakiety i piłki. Rakiety oferują doskonałą dynamikę, precyzję i komfort gry na każdym poziomie zaawansowania. Jednak, aby grać precyzyjnie, zawodnik musi odpowiednio wcześnie i dokładnie widzieć nadlatującą piłkę. Filc piłek Head jest o 19% jaśniejszy od innych piłek. Jest to zasługa technologii produkcji filcu Smart Optic Felt. Jaśniejsza piłka, nawet po wielu rozegranych gemach, jest lepiej widoczna i pozwala szybciej przygotować się do jej dobrego odegrania.', GETDATE());

INSERT INTO _dict_description_items(Name, InsertTime) VALUES (N'Zawodnicza rakieta do rekreacyjnej gry w tenisa ziemnego Head. Optymalna moc i czucie sprawią, że osiągniesz nowy poziom rozgrywki. Grafit nadaje rakiecie wysoki poziom wytrzymałości wytrzymałość, zapewnia optymalne wyważenie i skutecznie redukuje drgania. Zastosowane technologie dadzą Ci przewagę nad rywalem, a precyzyjne parametry ułatwią nadawać piłce więcej dynamiki i zabójczej rotacji podczas każdego zagrania. W sprzedaży z pełnym pokrowcem.', GETDATE());

INSERT INTO _dict_description_items(Name, InsertTime) VALUES (N'Rakieta do tenisa ziemnego wykonana z najmocniejszego i jednocześnie najlżejszego materiału na świecie. Graphene w połączeniu z Youtek pozwolił stworzyć rakietę, która zapewnia wszechstronność, doskonałe czucie, manewrowalność, precyzję i moc oraz dynamikę podczas gry na korcie. Pro to najbardziej agresywna rakieta z rodziny Radical. To większa waga, a więc i większa moc oraz żadnej litości dla rywala zza siatki. Jest polecana przez Andy Murraya dla doświadczonych pasjonatów tenisa i zawodowców. W sprzedaży bez naciągu.', GETDATE());